language: cpp

script:
    - ./setup.py install && ./setup.py test

matrix:
    include:
        - os: linux
            env:
                - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
            addons:
                apt:
                    sources: 
                        - ubuntu-toolchain-r-test 
                    packages:
                        - g++-7
                        - libclang 
    
    include:
        - os: linux
            env:
                - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
            addons:
                apt:
                    sources:
                        - llvm-toolchain-trusty-5.0
                    packages:
                        - libclang 
                        - clang-5.0

before_install:
    - eval ${MATRIX_EVAL}


